workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'develop'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'cicd'

variables:
  DOCKER_DRIVER: overlay2
  SRC_PATH: src
  NGINX_PATH: nginx
  DOCKER_VERSION_TAG: 27.4.1

generate tag:
  stage: .pre
  script:
    - formatted_date=$(date -u -D $CI_PIPELINE_CREATED_AT +"%Y%m%d%H%M%S")
    # - echo "BUILD_TAG=$formatted_date-$CI_COMMIT_REF_SLUG" >> .env
    - echo "BUILD_TAG=latest" >> .env
  artifacts:
    reports:
      dotenv: .env
  rules: 
    - changes:
        - $NGINX_PATH/**/*
        - $SRC_PATH/**/*
    - if: $CI_COMMIT_BRANCH == 'cicd'

build source:
  stage: build
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE/backend
  tags:
    - dockernaya
  image: docker:$DOCKER_VERSION_TAG-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - echo "$BACKEND_DOT_ENV_BASE_64" | base64 -d > ./.env
    - echo "build using $DOCKER_IMAGE_NAME:$BUILD_TAG name:tag"
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push "$DOCKER_IMAGE_NAME:$BUILD_TAG"
  rules:
    - changes:
      - $SRC_PATH/**/*
    - if: $CI_COMMIT_BRANCH == 'cicd'

build nginx:
  stage: build
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE/nginx
  tags:
    - dockernaya
  image: docker:$DOCKER_VERSION_TAG-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -t "$DOCKER_IMAGE_NAME" ./nginx
    - docker push "$DOCKER_IMAGE_NAME:$BUILD_TAG"
  rules:
    - changes:
      - $NGINX_PATH/**/*
    - if: $CI_COMMIT_BRANCH == 'cicd'
    

deploy nginx:
  stage: deploy
  tags:
    - curlitel
  script:
    - curl -k --request POST $DEPLOY_NGINX_WEBHOOK_URL
  rules:
    - changes:
      - $NGINX_PATH/**/*

deploy source:
  stage: deploy
  tags:
    - curlitel
  before_script:
    - apk add curl
  script:
    - curl -k --request POST $DEPLOY_SOURCE_WEBHOOK_URL
  rules:
    - changes:
      - $SRC_PATH/**/*