default:
  image: docker:27.4.1-cli
  services:
    - name: docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

variables:
  DOCKER_DRIVER: overlay2
  SRC_PATH: /src
  NGINX_PATH: /nginx

stages:
  - generate-tag
  - build
  - deploy

generate tag:
  stage: generate-tag
  script:
    - formatted_date=$(date -u -D $CI_PIPELINE_CREATED_AT +"%Y%m%d%H%M%S")
    # - echo "BUILD_TAG=$formatted_date-$CI_COMMIT_REF_SLUG" >> .env
    - echo "BUILD_TAG=latest" >> .env
  artifacts:
    reports:
      dotenv: .env
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - $NGINX_PATH/**/*
        - $SRC_PATH/**/*

build source:
  stage: build
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE/backend
  script:
    - echo "$BACKEND_DOT_ENV_BASE_64" | base64 -d > ./.env
    - echo "build using $DOCKER_IMAGE_NAME:$BUILD_TAG name:tag"
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push "$DOCKER_IMAGE_NAME:$BUILD_TAG"
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - $SRC_PATH/**/*
  
build-nginx:
  stage: build
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE/nginx
  script:
    - docker build -t "$DOCKER_IMAGE_NAME" ./nginx
    - docker push "$DOCKER_IMAGE_NAME:$BUILD_TAG"
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - $NGINX_PATH/**/*

deploy nginx:
  stage: deploy
  before_script:
    - apk add curl
  script:
    - curl -k --request POST $DEPLOY_NGINX_WEBHOOK_URL
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - $NGINX_PATH/**/*

deploy source:
  stage: deploy
  before_script:
    - apk add curl
  script:
    - curl -k --request POST $DEPLOY_SOURCE_WEBHOOK_URL
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - $NGINX_PATH/**/*