version: "3.0"
services:
  backend_api:
    image: ${CI_REGISTRY_IMAGE}/backend:latest
    ports:
      - "8001:8000"
    networks:
      - swarm-network
  nginx:
    image: ${CI_REGISTRY_IMAGE}/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/api.sangel.ru/fullchain.pem:/etc/nginx/sangel.cert:ro
      - /etc/letsencrypt/live/api.sangel.ru/privkey.pem:/etc/nginx/sangel.key:ro
    depends_on:
      - backend_api
    networks:
      - swarm-network

networks:
  swarm-network:
    driver: overlay
