version: "3.0"
services:
  backend_api:
    image: gitlab.sangel.ru:5005/backenders/sangelapi/backend:latest
    ports:
      - "8001:8000"
    networks:
      - swarm-network
  nginx:
    image: gitlab.sangel.ru:5005/backenders/sangelapi/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /server/sangel.cert:/etc/nginx/sangel.cert:ro
      - /server/sangel.key:/etc/nginx/sangel.key:ro
    depends_on:
      - backend_api
    networks:
      - swarm-network

networks:
  swarm-network:
    driver: overlay
