version: "3.0"
services:
  backend_api:
    build: .
    ports:
      - "8001:8000"
    secrets:
      - backend-secrets
    networks:
      - swarm-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /server/sangel.conf:/etc/nginx/conf.d/default.conf:ro
      - /server/sangel.cert:/etc/nginx/sangel.cert:ro
      - /server/sangel.key:/etc/nginx/sangel.key:ro
    depends_on:
      - backend_api
    networks:
      - swarm-network
secrets:
  backend-secrets:
    file: /server/.env
networks:
  swarm-network:
    driver: overlay
    attachable: true
