upstream api {
    server backend_api:8000;
}

server {
    listen 443 ssl;
    server_name api.sangel.ru;

        ssl_certificate /etc/nginx/sangel.cert;
        ssl_certificate_key /etc/nginx/sangel.key;


    location / {
        proxy_pass http://api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
proxy_redirect off;
    }
}

server {
    listen 80;
    server_name api.sangel.ru;

        ssl_certificate /etc/nginx/sangel.cert;
        ssl_certificate_key /etc/nginx/sangel.key;


    location / {
        proxy_pass http://api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
proxy_redirect off;
    }
}
