"""Initial tables

Revision ID: 7ed1d4b30393
Revises: 
Create Date: 2025-04-08 12:56:55.571674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed1d4b30393'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mac_address', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_products_mac_address'), 'device_products', ['mac_address'], unique=True)
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_link', sa.String(length=255), nullable=False),
    sa.Column('is_photo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('surname', sa.Text(), nullable=False),
    sa.Column('patronymic', sa.Text(), nullable=False),
    sa.Column('passport_series', sa.Text(), nullable=False),
    sa.Column('passport_number', sa.Text(), nullable=False),
    sa.Column('passport_agency', sa.Text(), nullable=False),
    sa.Column('passport_code', sa.Text(), nullable=False),
    sa.Column('passport_address', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registration_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("code ~ '^\\d{6}$'", name='check_verif_code_format'),
    sa.CheckConstraint("phone ~ '^\\+7\\d{10}$' OR phone ~ '^8\\d{10}$'", name='check_verif_code_phone_format'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visibility_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('patronymic', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=True),
    sa.Column('passport_id', sa.UUID(), nullable=True),
    sa.Column('visibility_type_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("email ~ '^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$'", name='check_users_email_format'),
    sa.CheckConstraint("name ~ '^[А-Яа-я-]+$'", name='check_users_name_cyrillic'),
    sa.CheckConstraint("patronymic ~ '^[А-Яа-я-]+$'", name='check_users_patronymic_cyrillic'),
    sa.CheckConstraint("phone ~ '^\\+7\\d{10}$' OR phone ~ '^8\\d{10}$'", name='check_users_phone_format'),
    sa.CheckConstraint("surname ~ '^[А-Яа-я-]+$'", name='check_users_surname_cyrillic'),
    sa.ForeignKeyConstraint(['passport_id'], ['passports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photo_id'], ['media.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visibility_type_id'], ['visibility_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('start_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('start_longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('complete_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('called_security_group', sa.Boolean(), nullable=False),
    sa.Column('called_users', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('-180 <= start_longitude AND start_longitude <= 180', name='check_longitude_range'),
    sa.CheckConstraint('-90 <= start_latitude AND start_latitude <= 90', name='check_latitude_range'),
    sa.CheckConstraint('complete_date > created_at', name='check_complete_after_created'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favourite_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('linked_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("name ~ '^[А-Яа-я-]+$'", name='check_favourite_name_cyrillic'),
    sa.CheckConstraint("phone ~ '^\\+7\\d{10}$' OR phone ~ '^8\\d{10}$'", name='check_favourite_phone_format'),
    sa.CheckConstraint('owner_id != linked_user_id', name='check_different_favourite_users'),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'phone', name='unique_favourite_contact')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_refresh_token'), 'tokens', ['refresh_token'], unique=True)
    op.create_table('user_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observers')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_tokens_refresh_token'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_table('notifications')
    op.drop_table('favourite_contacts')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('visibility_types')
    op.drop_table('verification_codes')
    op.drop_table('registration_tokens')
    op.drop_table('passports')
    op.drop_table('media')
    op.drop_index(op.f('ix_device_products_mac_address'), table_name='device_products')
    op.drop_table('device_products')
    # ### end Alembic commands ###
