"""Update tables, added current coords

Revision ID: 91c0dbbc3c8d
Revises: dfafe58928e5
Create Date: 2025-04-13 19:23:17.004389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c0dbbc3c8d'
down_revision: Union[str, None] = 'dfafe58928e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('current_latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('events', sa.Column('current_longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'current_longitude')
    op.drop_column('events', 'current_latitude')
    # ### end Alembic commands ###
