"""Updated tables

Revision ID: dfafe58928e5
Revises: 7ed1d4b30393
Create Date: 2025-04-09 13:13:45.450685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfafe58928e5'
down_revision: Union[str, None] = '7ed1d4b30393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Text(), nullable=False),
    sa.Column('validity_period', sa.Text(), nullable=False),
    sa.Column('cvv_number', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('card_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'cards', ['card_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'card_id')
    op.drop_table('cards')
    # ### end Alembic commands ###
